services:
  app:
    deploy:
      mode: detach
    image: tatame-digital
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: arenasenha

  database:
    deploy:
      mode: detach
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_PASSWORD: arenasenha
    ports:
      - 5432:5432
    volumes:
      - arena_postgres_data:/var/lib/postgresql/data
volumes:
  arena_postgres_data: